const S={slots:[0,1,0,1],forced:0,em:false,entry:1,exit:0,notes:[]};const names={home:'Live Dashboard',parking:'Parking Area',analytics:'Parking Analytics',security:'Security Center',alerts:'Notifications',settings:'Settings'};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.s).classList.add('active');document.getElementById('title').textContent=names[b.dataset.s]});
function slots(id){document.getElementById(id).innerHTML=S.slots.map((v,i)=>`<div class="slot ${v?'occ':'free'}"><b>SLOT ${String(i+1).padStart(2,'0')}</b><small>${v?'Vehicle detected':'Available for parking'}</small><span class="badge">${v?'OCCUPIED':'AVAILABLE'}</span><span class="car">${v?'🚙':'🚗'}</span></div>`).join('')}
function render(){let o=S.slots.reduce((a,b)=>a+b,0),f=4-o,p=o*25;['occ'].forEach(x=>document.getElementById(x).textContent=o);document.getElementById('free').textContent=f;document.getElementById('pct').textContent=p+'%';document.getElementById('hp').textContent=p+'%';document.getElementById('pt').textContent=p+'%';document.getElementById('bar').style.width=p+'%';let r=S.slots.findIndex(x=>!x);document.getElementById('rec').textContent=r<0?'FULL':'SLOT '+String(r+1).padStart(2,'0');document.getElementById('eg').textContent=S.entry?'OPEN':'CLOSED';document.getElementById('xg').textContent=S.exit?'OPEN':'CLOSED';document.getElementById('entryGateCard').classList.toggle('gate-closed',!S.entry);document.getElementById('exitGateCard').classList.toggle('gate-closed',!S.exit);document.getElementById('em').textContent=S.em?'ACTIVE':'NORMAL';document.getElementById('fc').textContent=S.forced;document.getElementById('sc').textContent=S.forced;slots('map');slots('large');document.getElementById('forcedStatus').textContent=S.forced?'DETECTED':'NORMAL';document.getElementById('forcedCount').textContent=S.forced+(S.forced===1?' event':' events');document.getElementById('emergencyStatus').textContent=S.em?'ACTIVE':'NORMAL';document.getElementById('emergencyGates').textContent=S.em?'Both gates OPEN':'Gates secured';document.getElementById('forcedMini').classList.toggle('active',S.forced>0);document.getElementById('emergencyMini').classList.toggle('active',S.em);slots('map');slots('large')}
function note(a,b){S.notes.unshift({a,b,time:'just now'});renderNotes();}
function renderNotes(){const html=S.notes.slice(0,8).map(n=>`<div class="note"><b>${n.a}</b><small>${n.b} · ${n.time}</small></div>`).join('');document.getElementById('notes').innerHTML=html||'<div class="empty">🟢 No alerts yet</div>';const dash=S.notes.slice(0,3).map((n,i)=>`<div class="dash-note ${i===0 && (n.a.includes('FORCED')||n.a.includes('EMERGENCY'))?'critical':''}"><span>${n.a.split(' ')[0]}</span><div><b>${n.a.substring(n.a.indexOf(' ')+1)}</b><small>${n.b} · ${n.time}</small></div></div>`).join('');document.getElementById('dashboardNotes').innerHTML=dash||'<div class="empty">🟢 No active alerts</div>';}
function forced(){S.forced++;document.getElementById('securityCard').classList.add('alert');document.getElementById('ss').textContent='FORCED ENTRY DETECTED';document.getElementById('st').textContent='Security alert active. Alarm and notification triggered.';note('🚨 FORCED ENTRY','Unauthorized gate crossing detected');render();toast('Security notification sent')}
function emergency(){S.em=!S.em;S.entry=S.em?1:0;S.exit=S.em?1:0;document.getElementById('securityCard').classList.toggle('alert',S.em);document.getElementById('ss').textContent=S.em?'EMERGENCY MODE ACTIVE':'SYSTEM SECURE';document.getElementById('st').textContent=S.em?'Both gates are open for emergency operation.':'No active security alert.';if(S.em)note('⚠️ EMERGENCY MODE','Both gates opened');render();toast(S.em?'Emergency mode activated':'Emergency mode cleared')}
function showScreen(id){document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.s===id));document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.getElementById('title').textContent=names[id]}
function toast(t){let x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2000)}
let vals=[20,35,48,65,82,100,75,58,70,45,62,50];document.getElementById('bars').innerHTML=vals.map(v=>`<i style="height:${v}%"></i>`).join('');note('🟢 SYSTEM ONLINE','ESP32 connected and sending live data');renderNotes();render();setInterval(()=>{let i=Math.floor(Math.random()*4);S.slots[i]^=1;render()},7000);
function demoSlot(){let i=S.slots.findIndex(v=>!v);if(i<0){toast('Parking is full');note('🅿️ PARKING FULL','No available slots');return}S.slots[i]=1;note('🅿️ SLOT '+String(i+1).padStart(2,'0')+' OCCUPIED','Vehicle detected and guidance updated');render();toast('Vehicle parked in Slot '+(i+1))}
function gateDemo(){['entryGateCard','exitGateCard'].forEach(id=>{let e=document.getElementById(id);e.classList.remove('gate-moving');void e.offsetWidth;e.classList.add('gate-moving');setTimeout(()=>e.classList.remove('gate-moving'),700)});toast('Gate animation running')}
